### ISSUE TITLE
[Question] Is it possible to keep schema file out of /lib folder?

### ISSUE THREAD

**Issue by amadeu01** [comigor/artemis#11]
I tried to keep `my.schema.json` file in the root directory of the flutter app (one directory before `/lib`). But, the files couldn't be generated.

```
targets:
  $default:
    sources:
      - lib/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: my.schema.json
              queries_glob: lib/**.query.graphql
              resolve_type_field: __typename
```

Then, I try to use `schema: ./my.schema.json`, but didn't work as well.
And then, I tried to use `schema: lib/my.schema.json` and also moved the file to inside `/lib` folder, so it managed to work well and generate the files.

**Comment by comigor** [comment]
Well that's strange, I've tried to reference a schema from the root.
Maybe there's something wrong in the way builder queries for input files?
I'll take a look at it!

**Comment by comigor** [comment]
Well, it seems it's possible for `build` to [get files outside `lib/` folder](https://github.com/dart-lang/build/blob/db7af3d9868e84c554ed93314df5469ad5e9c142/build_test/test/test_builder_test.dart#L53-L74) (at least if if uses the special `$lib` placeholder for input files.)

I'll try to make Artemis use it instead of `*.query.graphql` files as input.

**Comment by comigor** [comment]
Well, even though this test assures that it's possible: it is NOT. I've created the same builder as this test and could find assets under `data/*`, on the root of project, even if using `$lib$`.
So yeah, I'm kinda blocked on this by `builder`.

**Comment by comigor** [comment]
I've just opened up an issue on builder repo: https://github.com/dart-lang/build/issues/2426

**Comment by comigor** [comment]
It seems they whitelist [some inputs](https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/options.dart#L21-L31).

**Comment by comigor** [comment]
Hey @amadeu01, I've digged into `build` code and found out that you need to explicitly whitelist the input globs you want to be parsed, or else `build` will use by default [the inputs I've posted above](https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/options.dart#L21-L31).

To do so, just change your `build.yaml`:
```
targets:
  $default:
    sources:
      - lib/**
      - my.schema.json
```

Or I guess you could just whitelist everything:
```
targets:
  $default:
    sources:
      - **
```
