### ISSUE TITLE
Enum type names have funky names

### ISSUE THREAD

**Issue by emme1444** [comigor/artemis#112]
I have the following `mutation` written in a file that is built by `artemis`: 
```graphql
mutation ExternalAuthenticate(
    $provider: AuthProvider!
    $email: String!
    $username: String!
) {
    externalAuthenticate(
        provider: $provider
        email: $email
        username: $username
    )
}
```

AuthProvider is an enum, and works perfectly in, say, the GraphQL Playground. However, the artemis generated output does not contain this enum type. I get an error in the output, for the variable arguments of the mutation that tells me the class is undefined. 

```dart
@JsonSerializable(explicitToJson: true)
class ExternalAuthenticateArguments extends JsonSerializable with EquatableMixin {
  ExternalAuthenticateArguments({this.provider, this.email, this.username});

  factory ExternalAuthenticateArguments.fromJson(Map<String, dynamic> json) =>
      _$ExternalAuthenticateArgumentsFromJson(json);

  final AuthProvider provider; // Undefined class 'AuthProvider'.

  final String email;

  final String username;

  @override
  List<Object> get props => [provider, email, username];
  Map<String, dynamic> toJson() => _$ExternalAuthenticateArgumentsToJson(this);
}
```

Here is my `build.yaml`:
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
      - my.schema.json
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: my.schema.json
              queries_glob: lib/graphql/**.graphql
              output: lib/graphql_api.dart
```
