### ISSUE TITLE
Unknown definition type 'createdAt' (timestamptz)

### ISSUE THREAD

**Issue by FickleLife** [comigor/artemis#125]
I am trying to generate classes from an hasura GQL endpoint, schema generated by graphqurl. I am getting an error:

```
[SEVERE] artemis:artemis on lib/$lib$:

Error on line 629, column 3 of lib/graphql/schema.graphql: Unknown definition type 'createdAt'
    ╷
629 │   createdAt: timestamptz
    │   ^^^^^^^^^
    ╵
```

assuming I would need to do a custom mapping as timestamptz is a postgres thing, my build.yaml looks like this:

```
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - data/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: lib/my_graphql_schema.graphql
              queries_glob: lib/**.graphql
          scalar_mapping:
            - graphql_type: timestamptz
              dart_type: DateTime
```

the schema in /lib/graphql/schema.graphql is https://paste.ubuntu.com/p/Mpw5wHMVWN/

Any ideas how I can get timestamptz to map?

**Comment by FickleLife** [comment]
I have had a closer look a the custom scalar parsers. My build.yaml looks like

```
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - data/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: lib/my_graphql_schema.graphql
              queries_glob: lib/**.graphql
          custom_parser_import: 'package:boatabout_app/services/artemis_timeconvert.dart'
          scalar_mapping:
            - graphql_type: Timestamptz
              dart_type: DateTime
              use_custom_parser: true
```

artemis_timeconvert.dart looks like:

```
import 'package:intl/intl.dart';

final dateFormatter = DateFormat('yyyy-MM-ddTHH:mm:ssZ');

DateTime fromGraphQLTimestamptzToDartDateTime(String timestamptz) => DateTime.parse(timestamptz);
String fromDartDateTimeToGraphQLTimestamptz(DateTime timestamptz) => dateFormatter.format(timestamptz);
```
but I am still getting the same error....

**Comment by vasilich6107** [comment]
I did not succeed in `use_custom_parser: true`

Here is a sample of `scalar_mapping`  that works for me

```
 scalar_mapping:
            - graphql_type: Upload
              custom_parser_import: '.../helpers/artemis.dart'
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'
            - graphql_type: DateTime
              custom_parser_import: 'package:running_hours/helpers/artemis.dart'
              dart_type: DateTime
```

**Comment by FickleLife** [comment]
Thanks for the reply @vasilich6107 - I've checked a few things...

I've adjusted my build.yaml to reflect yours, checked the schema and can see `scalar timestamptz` and also the definition seems to be correct - 

```type tripTemplate {
  createdAt: timestamptz
```
Same error unfortunately. Have tried searching the Artemis source for the error message "Unknown definition type" but can't find it... Do you know of any other way to debug to understand the issue?

**Comment by vasilich6107** [comment]
What artemis version are you using?

**Comment by FickleLife** [comment]
artemis: ^5.1.0

**Comment by vasilich6107** [comment]
Try 6.0.6 beta

**Comment by FickleLife** [comment]
just upgraded to `artemis: ^6.0.6-beta.1`, same issue unfortunately (ran `flutter clean` beforehand)

**Comment by comigor** [comment]
Hey @FickleLife!
Well, though this schema seems a little "strange" (the variables capitalization don't comply with GraphQL spec), I see no reason why they wouldn't work. I'll take a look.

**Comment by comigor** [comment]
So, @FickleLife!

Weird as it seems, the error happens because you have some "blank comments" (lines with only `#` followed by line terminator) on your schema.graphql file 😂 

If you remove them, Artemis will probably work!

I've opened an issue on the relevant parser repository (https://github.com/gql-dart/gql/issues/99) and will try to fix it by myself, bumping Artemis after that.

**Comment by FickleLife** [comment]
Right, yes very weird! I'll strip or add comments and work around for now. 

Thanks so much for taking the time to look at it.

**Comment by FickleLife** [comment]
Hi @comigor, there were three empty comment blocks which I have removed (new schema: https://paste.ubuntu.com/p/4Gh6yyCFB4/  ), and am now getting: 
```
[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[SEVERE] artemis:artemis on lib/$lib$:

Bad state: No element
[INFO] 1.2s elapsed, 1/17 actions completed.
[INFO] 2.5s elapsed, 1/17 actions completed.
```

I've googled around and at the risk of not starting another thread, any ideas what could be up? The build.yaml is 
```
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/graphql_api.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/**.graphql
```
