### ISSUE TITLE
type 'ListTypeNode' is not a subtype of type 'NamedTypeNode' in type cast

### ISSUE THREAD

**Issue by SwannLV** [comigor/artemis#126]
Hello! 

I have this error when building: ` type 'ListTypeNode' is not a subtype of type 'NamedTypeNode' in type cast`

This is caused by this field in my schema.gql: 
`myField: [[ID]]`

Thank you 🙏🙂

**Comment by vasilich6107** [comment]
Could you provide complete shema sample and your query?

**Comment by SwannLV** [comment]
Sure: [build-error.zip](https://github.com/comigor/artemis/files/4580466/build-error.zip)

'myField' is the problem.

- schema.gql:
```
type Query {
  countries: [Country]

  search(filters: MissionSearchInput!): Items
}

input Input {
  myField: [[ID]]
}

type Items {
  id: String
  count: Int
}

type Country {
  id: String!
  iso2: String!
  iso3: String!
  name: String!
  phonePrefix: String!
}
```

- query.gql :
```
query MyQuery {
  countries{
    id
  }
} 
```

- build.yaml:
```
targets:
  $default:
    builders:
      artemis:
        options:
          generate_helpers: true
          fragments_glob: lib/**fragment.graphql
          schema_mapping:
            - queries_glob: lib/query.gql
              schema: lib/schema.graphql
              output: lib/graphql/types.dart
```
