### ISSUE TITLE
"Bad state: No element" trying to generate against any schema

### ISSUE THREAD

**Issue by FickleLife** [comigor/artemis#132]
I am trying to generate against any graphql schema and the builder returns `Bad state: No element`

I have:
- `flutter pub cache repair`
- `flutter clean`
- tried all artemis versions 5.1.0 to 6.0.7beta1
- tried dependent package versions recommended in docs, and the latest versions also  
- tried several different schemas, including https://developer.github.com/v4/public_schema/

I always get `Bad state: No element`

My build.yaml
```
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/graphql_api.dart
              schema: lib/graphql/schema.public.graphql #github
              queries_glob: lib/graphql/**.graphql
```

pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7
  font_awesome_flutter: ^8.8.1
  artemis: ^5.1.0
  graphql_flutter: ^3.0.0
  cloud_functions: ^0.4.1
  provider: 4.0.5+1
  firebase_auth: ^0.11.1+11
  equatable: ^1.1.1
  path_provider: ^1.6.7
  meta: ^1.1.8 # only if you have non nullable fields
  gql: ^0.12.3
  json_annotation: ^3.0.1
  intl: ^0.16.1
  scaffold_tab_bar: ^0.0.2
  flutter_map: ^0.9.0
  settings_ui: ^0.2.0
  flutter_sticky_header: ^0.4.2
  json_serializable: ^3.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  artemis: ^5.1.0
  json_serializable: ^3.3.0
```

the trace of the error:
```
➜  boatabout_app git:(dev) ✗ flutter pub run build_runner build --verbose
[INFO] Generating build script...
[INFO] Generating build script completed, took 703ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 111ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 891ms

[INFO] Build:Running build...
[SEVERE] artemis:artemis on lib/$lib$:

Bad state: No element
dart:core                                                               Iterable.first
package:artemis/generator.dart 98:65                                    generateQuery
package:artemis/generator.dart 33:21                                    generateLibrary.<fn>
dart:_internal                                                          ListIterable.toList
package:artemis/generator.dart 41:8                                     generateLibrary
package:artemis/builder.dart 129:29                                     GraphQLQueryBuilder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 486:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 484:23           _SingleBuild._runForInput.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 441:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 437:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 375:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 374:36           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 320:20           _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 184:15  _NoOpBuildPerformanceTracker.trackBuildPhase
package:build_runner_core/src/generate/build_impl.dart 316:47           _SingleBuild._runPhases.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 310:32           _SingleBuild._runPhases
package:build_runner_core/src/logging/logging.dart 25:30                logTimedAsync
package:build_runner_core/src/generate/build_impl.dart 267:26           _SingleBuild._safeBuild.<fn>
dart:async                                                              runZoned
package:build_runner_core/src/generate/build_impl.dart 262:5            _SingleBuild._safeBuild
package:build_runner_core/src/generate/build_impl.dart 209:24           _SingleBuild.run
package:build_runner_core/src/generate/build_impl.dart 94:56            BuildImpl.run
package:build_runner_core/src/generate/build_runner.dart 25:14          BuildRunner.run
package:build_runner                                                    BuildCommand.run
package:args/command_runner.dart 197:27                                 CommandRunner.runCommand
package:args/command_runner.dart 112:25                                 CommandRunner.run.<fn>
dart:async                                                              new Future.sync
package:args/command_runner.dart 112:14                                 CommandRunner.run
package:build_runner                                                    run
.dart_tool/build/entrypoint/build.dart 31:22                            main

[INFO] Build:Running build completed, took 744ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 65ms

[SEVERE] Build:
Failed after 823ms
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:376:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:760:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:657:33)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _runZoned (dart:async/zone.dart:1619:10)
#10     runZoned (dart:async/zone.dart:1539:10)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:647:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZoned (dart:async/zone.dart:1539:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:289:19)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:112:14)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:232:18)
#27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _runZoned (dart:async/zone.dart:1619:10)
#31     runZonedGuarded (dart:async/zone.dart:1608:12)
#32     runZoned (dart:async/zone.dart:1536:12)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#34     run.<anonymous closure> (package:flutter_tools/runner.dart)
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:63:18)
<asynchronous suspension>
#36     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#38     _rootRun (dart:async/zone.dart:1184:13)
#39     _CustomZone.run (dart:async/zone.dart:1077:19)
#40     _runZoned (dart:async/zone.dart:1619:10)
#41     runZoned (dart:async/zone.dart:1539:10)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#43     runInContext (package:flutter_tools/src/context_runner.dart:66:24)
#44     run (package:flutter_tools/runner.dart:47:10)
#45     main (package:flutter_tools/executable.dart:68:9)
#46     main (file:///Applications/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Any ideas where I am going wrong?

**Comment by comigor** [comment]
Hey @FickleLife, can you post your query as well?

I'm able to successfully generate GitHub queries on Artemis.

**Comment by FickleLife** [comment]
Thanks @comigor 

GitHub schema I've been trying to build with: https://developer.github.com/v4/public_schema/schema.public.graphql

My own schema, now generated with get-graphql-schema (doesn't use # comments): https://paste.ubuntu.com/p/KFpNs7wHyb/

**Comment by comigor** [comment]
@FickleLife But what about the queries? Artemis generate the files based on the query, rather than the whole schema.

**Comment by FickleLife** [comment]
Apologies, I didn't have a query. I was following the docs closely and not the [ultimate toolchain](https://medium.com/@v.ditsyak/ultimate-toolchain-to-work-with-graphql-in-flutter-13aef79c6484) guide. I can see everything generating now. 

Thanks for your help and apologies for the simple error.

**Comment by comigor** [comment]
No problem! Feel free to reach again with any other doubt!

**Comment by briblanch** [comment]
@comigor I am seeing the same `Bad State: no element` error that @FickleLife  was seeing. Here is my test query and schema I am using

https://gist.github.com/briblanch/17511a15d183464d20959bd5068da25a

Any ideas?

**Comment by comigor** [comment]
Hey @briblanch, how are you doing?
Can you please post your `build.yaml` configuration as well?

**Comment by RodolfoSilva** [comment]
I fixed this problem changing the glob expression: 
```yaml
queries_glob: graphql/*.{query,subscription,mutation}.graphql
```

**Comment by briblanch** [comment]
My build.yaml is

```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/src/graphql.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/**.graphql
```
