### ISSUE TITLE
Fragments generate same classes on beta

### ISSUE THREAD

**Issue by SanjiKir** [comigor/artemis#137]
**Bug description**
When using fragment, which requests enums or nested data structures, in multiple queries I have this error: 

```
Two classes were generated with the same name `OrderState`!
You may want to:
- Make queries_glob stricter, to gather less .graphql files on a single output
- Use alias on one of the places a field of type `AccountingItemState` is requested
- Change naming_scheme to `pathedWithFields` to avoid duplication
```
where AccountingItemState represents enum. If I delete this field error doesn't go away.  This one comes in

```
Two classes were generated with the same name `OrderFieldsMixin$Place`!
You may want to:
- Make queries_glob stricter, to gather less .graphql files on a single output
- Use alias on one of the places a field of type `OrderFieldsMixin$Place` is requested
- Change naming_scheme to `pathedWithFields` to avoid duplication
```

**Specs**
`6.0.9-beta.1`
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: lib/graphql/fragments/*.graphql
          scalar_mapping:
            - graphql_type: Date
              custom_parser_import: 'package:name/coercers.dart'
              dart_type: DateTime
          schema_mapping:
            - schema: schema.graphql
              queries_glob: lib/graphql/operations/**.graphql
              output: lib/graphql_api.dart
```

Fragment
```
fragment orderFields on Order {
    __typename
    id
    createdUtc
    updatedUtc
    orderState
    place {
      id
    }
```

Order scheme
```
type Order {
  id: ID!
  createdUtc: Date!
  closedUtc: Date
  updatedUtc: Date
  orderState: OrderState!
  venue: Venue!
  place: Place
....
```

I guess the expected behavior should be not to generate multiple classes for a single fragment? I've seen an issue like  https://github.com/comigor/artemis/pull/65, I believe it should have solved it, but it looks there is a bug or maybe I am dumb and doing something wrong IDK.

**Comment by Diligas-a** [comment]
I have the same problem

**Comment by vasilich6107** [comment]
We are working on this issue

For you can try this brach(works perfectly in my project)

```
artemis:
    git:
      url: https://github.com/comigor/artemis.git
      ref: temp/dedup-fix-on-beta
```

**Comment by danielmahon** [comment]
@vasilich6107 Your branch is working but is there a way to dedupe the Fragment Mixins as well? Since Dart doesn't handle type unions I'm having all kinds of issues trying to use a model returned multiple ways from GraphQL. For a model "Tool" that can be returned from queries/mutations/subscriptions every parsed type is different, by using the same fragment across all three I seemingly can have my views/etc expect a "ToolFragment" mixin which "should" work. But right now that fragment is duplicated for queries/mutations/subscriptions. Is there a way to make them all reference the same mixin? Or is there a better way I'm missing?

On a side note, any chance of merging in the latest beta for more subscription support?

**Comment by vasilich6107** [comment]
Try this branch `bugfix/deduplication` it is a branch I'm working on to fix the issue.
I'll be testing it on my project

**Comment by Diligas-a** [comment]
> 
> 
> Try this branch `bugfix/deduplication` it is a branch I'm working on to fix the issue.
> I'll be testing it on my project
> It is from latest beta)

Thank you, it helps me!  👍

**Comment by vasilich6107** [comment]
@Diligas-a @danielmahon @SanjiKir 
Could you check the 6.0.10-beta.1

**Comment by Diligas-a** [comment]
> @Diligas-a @danielmahon @SanjiKir 
> 
> Could you check the 6.0.10-beta.1

It’s working for me. 🙏

**Comment by danielmahon** [comment]
> @Diligas-a @danielmahon @SanjiKir
> Could you check the 6.0.10-beta.1

Seems to be working for me as well! 🎉 

build.yaml
```yaml
          scalar_mapping: ...
          fragments_glob: lib/graphql/fragments/**.graphql
          schema_mapping:
            - schema: lib/graphql/schema.g.graphql
              queries_glob: lib/graphql/{mutations,queries,subscriptions}/**.graphql
              output: lib/graphql/api.graphql.dart
              naming_scheme: pathedWithFields
```
