### ISSUE TITLE
Generate class for custom Input type

### ISSUE THREAD

**Issue by RodolfoSilva** [comigor/artemis#145]
**Bug description**
When I've a mutation with a scalar input, the classes of this input type is not created.
@comigor I'm using hasura, the problem occurs when i try create an insert_* mutation.

```gql
mutation add_product($payload: product_insert_input!) {
    insert_product_one(object: $payload) {
        id
        name
        price
    }
}
```

The artemis is not generating a class for the `product_insert_input`

**Specs**
Artemis version: [e.g. 6.0.3-beta.1]
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: graphql/**.fragment.graphql
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/*.{query,subscription,mutation}.graphql
              output: lib/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
          scalar_mapping:
            - graphql_type: appointment_status
              dart_type: String
            - graphql_type: uuid
              dart_type: String
            - graphql_type: timestamptz
              dart_type: DateTime
            - custom_parser_import: 'package:sw/coercers.dart'
              graphql_type: money
              dart_type: double
            - graphql_type: product_insert_input
              dart_type: dynamic
```
</details>
