### ISSUE TITLE
Undefined class Upload

### ISSUE THREAD

**Issue by thanhbinh84** [comigor/artemis#155]
**Bug description**
**Steps to reproduce:** 
- Create update_identity.graphql 
- Add content 
```
mutation UpdateIdentity ($identityPhoto: Upload!)  {
    updateIdentity(
        identityPhoto: $identityPhoto
    )
}

```
- Run `flutter pub run build_runner build`
Please describe what happened wrong and the expected behaviour/output.
Error: Undefined class Upload in graphql_api.graphql.dart file 
**Specs**
Artemis version: [^6.0.4-beta.1]
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - my.schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: graphql/fragments/common.graphql
          schema_mapping:
            - schema: my.schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/libs/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
# Please paste the output of
$ flutter pub run build_runner build --verbose
#or
$ pub run build_runner build --verbose
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 370ms

[WARNING] build.fallback:
The package `abc` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 99ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 902ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 25ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 57ms

[INFO] Build:Succeeded after 92ms with 0 outputs (0 actions)
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
# If possible, please paste your GraphQL schema file,
# or a minimum reproducible schema of the bug.
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
schema {
    query: Query
    mutation: Mutation
}
type Mutation {
    updateIdentity(identityPhoto: Upload!): Boolean
}
"The `Upload` scalar type represents a file upload."
scalar Upload

# If possible, please paste your GraphQL query file,
# or a minimum reproducible query of the bug.
```
</details>
