### ISSUE TITLE
Error when using [input] types and variables with a mutation 

### ISSUE THREAD

**Issue by FickleLife** [comigor/artemis#166]
**Bug description**
When creating a mutation to insert a large, multi-nested payload via a variable, I use an input type of [product_insert_input] which Hasura defines. Artemis cannot generate types for this (I am not sure types are needed as they are already defined) and the generated code has an error: `The name 'product_insert_input' isn't a type so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'product_insert_input'.`

I can see the input type [product_insert_input] appears to be defined correctly in the gql schema.

```
"""
input type for inserting data into table "product"
"""
input product_insert_input {
  barcode: String
  brand: brand_obj_rel_insert_input
  brandId: Int
  countryAlpha2Packaged: String
  countryAlpha2ProductOf: String
  countryPackaged: country_obj_rel_insert_input
  countryProductOf: country_obj_rel_insert_input
  createdAt: timestamptz
  createdBy: String
  id: Int
  ingredients: productIngredients_arr_rel_insert_input
  name: String
  updatedAt: timestamptz
  updatedBy: String
  weightGrams: Int
}
```

I'll freely admit I could be doing this all the wrong way too! What is the correct way to work with complex nested mutations using variables and have it play nice with Artemis? 

**Specs**
Artemis version: artemis: ^6.2.1-beta.1
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/schema/koalaroo.schema.graphql
              queries_glob: lib/graphql/data/**/**.graphql
              output: lib/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: timestamptz
              custom_parser_import: 'package:koalaroo_app/services/artemis_timeconvert.dart'
              dart_type: DateTime
```
</details>
<details>
<summary>Artemis output:</summary>
  
https://paste.ubuntu.com/p/Njj385DX4Q/

</details>
<details>
<summary>GraphQL schema:</summary>

https://paste.ubuntu.com/p/vQkBzybZZB/

</details>
<details>
<summary>GraphQL query:</summary>

```graphql
mutation addProduct($product: [product_insert_input!]!) {
  insert_product(objects: $product, on_conflict: {constraint: product_pkey, update_columns: barcode}) {
    affected_rows
    returning {
      id
    }
  }
}
```
variable payload:
```json
{
    "product": {
        "name": "Reflex Ultra White TEST",
        "barcode": "9311995002018",
        "countryAlpha2Packaged": "AU",
        "countryAlpha2ProductOf": "AU",
        "weightGrams": 3000,
      "brandId": 7,
        "ingredients": {
            "data": [
                {
                    "countryAlpha2": "AU",
                    "percentage": 70,
                    "desc": "au TEST demo data"
                },
                {
                    "countryAlpha2": "NZ",
                    "percentage": 30,
                    "desc": "Nz demo data"
                }
            ]
        }
    }
}

```
</details>
