### ISSUE TITLE
Annotate overridden members

### ISSUE THREAD

**Issue by dw2kim** [comigor/artemis#177]
**Bug description**
After generating the graphql.dart, there is warning:
info: Annotate overridden members. (annotate_overrides at ...)

**Specs**
Artemis version: >=5.0.0 <6.0.0
<details>
<summary>build.yaml:</summary>

```
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/src/service/gql/models/schema.dart
              schema: lib/src/service/gql/models/schema.graphql
              queries_glob: lib/src/service/gql/queries/**.graphql
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true
```

</details>
<details>
<summary>Artemis output:</summary>
  
```bash
# Please paste the output of
$ flutter pub run build_runner build --verbose
#or
$ pub run build_runner build --verbose
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
@JsonSerializable(explicitToJson: true)
class AppointmentArguments extends JsonSerializable with EquatableMixin {
  AppointmentArguments({@required this.id});

  factory AppointmentArguments.fromJson(Map<String, dynamic> json) =>
      _$AppointmentArgumentsFromJson(json);

  final String id;

  @override
  List<Object> get props => [id];
**HERE: We need the Override annotation. We are putting it manually right now**
  Map<String, dynamic> toJson() => _$AppointmentArgumentsToJson(this);
}
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
query appointment($id: String!) {
  appointment(id: $id) {
    id
    serviceCode {
      id
      name
      icon {
        key
      }
      description
      trade {
        id
        name
        blackoutPeriod {
          id
          message
          isNonContractOnly
          days
        }
      }
    }
    serviceZone {
      id
      name
      timezone
    }
  }
}
```
</details>
