### ISSUE TITLE
artemisUnknown enum generated when there doesn't appear to be any unknowns

### ISSUE THREAD

**Issue by FickleLife** [comigor/artemis#179]
**Bug description**
When building, I get several errors in `graphql_api.graphql.dart` as every table that has some constraint on it appears to generate an "artemisUnknown" enum. The generated code is (`graphql_api.graphql.dart`):
```dart
  @JsonKey(unknownEnumValue: BrandConstraint.artemisUnknown)
  BrandConstraint constraint;

  @JsonKey(name: 'update_columns')
  List<BrandUpdateColumn> updateColumns;
```
the above generates a couple of errors `Undefined name 'BrandConstraint'` and `The name 'BrandUpdateColumn' isn't a type so it can't be used as a type argument`.  Further down the file:

```dart
enum brand_constraint {
  @JsonValue("brand_name_key")
  brandNameKey,
  @JsonValue("brand_pkey")
  brandPkey,
  @JsonValue("ARTEMIS_UNKNOWN")
  artemisUnknown,
}
```
Looking at the enums for BrandConstraint in my schema:

```graphql
"""
unique or primary key constraints on table "brand"
"""
enum brand_constraint {
  """unique or primary key constraint"""
  brand_name_key

  """unique or primary key constraint"""
  brand_pkey
}

```
I am not sure where the third "unknown" enum is coming from. A clue could be that this error only presents itself when adding a mutation with an input type (see below for mutation code). Mutations that split out each field into its own variable do not present this issue. 

The backend service is Hasura.

**Specs**
Artemis version: ^6.4.4-beta.1
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/schema/koalaroo.schema.graphql
              queries_glob: lib/graphql/data/**/**.graphql
              output: lib/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: timestamptz
              custom_parser_import: 'package:strayan_app/services/artemis_timeconvert.dart'
              dart_type: DateTime
            - graphql_type: jsonb
              dart_type: dynamic
```
</details>
Artemis output: https://gist.github.com/FickleLife/1b089eec16f6b03e0b90ff6da84bc79b 

GraphQL schema: https://gist.github.com/FickleLife/de43d6aab9f08fc2172f90d1131cd3b9

GraphQL query:
This error only presents itself when adding a mutation with an input type. Mutations that split out each field into it's own variable do not present this issue. This is the mutation I am trying to add:

```graphql
mutation ProductInsertOne2($payload: product_insert_input!) {
  insert_product_one(object: $payload) {
    __typename
    id
    brand {
      __typename
      id
    }
    productTags {
      __typename
      id
    }
  } 
}
```
