### ISSUE TITLE
Exception: Two classes were generated with the same name 

### ISSUE THREAD

**Issue by MattGson** [comigor/artemis#189]
**Bug description**
Code generation fails with: `Exception: Two classes were generated with the same name `
This occurs because a node has two different children with the same exact type.

In the example query below, `friends` and `notfriends` have the same type `friendConnection`

The generated class name for both is:
`UserFriends$Query$Node$User$FriendsConnection$User`

**Specs**
Artemis version: 5.1.0
<details>
<summary>build.yaml:</summary>
  
```yaml
artemis:
        options:
          schema_mapping:
            - schema: graphql/km-schema.graphql
              queries_glob: lib/**.graphql
              output: lib/graphql/gen/graphql_api.dart
              # Naming options discussed here: https://github.com/comigor/artemis/pull/96
              naming_scheme: pathedWithFields
              type_name_field: __typename
```

</details>
<details>
<summary>GraphQL query:</summary>

```graphql
node(id: $id) {
        ... on User {
            id
            __typename
            friends(first: 10) {
                nodes {
                    id
                    name
                }
            }
            notFriends(first: 10) {
                nodes {
                    id
                    name
                }
            }
       }
}
```
</details>
