### ISSUE TITLE
Dart type with import fails as 'Invalid json'

### ISSUE THREAD

**Issue by jifalops** [comigor/artemis#213]
**Bug description**
I'm trying to have the generated output import a file so that the custom type is defined. 

**Specs**
Artemis version: 5.1.0
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          scalar_mapping:
            - custom_parser_import: 'package:graphbrainz_example/coercers.dart'
              graphql_type: BigDecimal
              dart_type:
                name: Decimal
                imports:
                  - 'package:decimal/decimal.dart'
```
</details>

  It always throws here

```dart
factory DartType.fromJson(dynamic json) {
    if (json is String) {
      return DartType(name: json);
    } else if (json is Map<String, dynamic>) {
      return _$DartTypeFromJson(json);
    } else {
      throw 'Invalid json: $json';
    }
  }
```

I've tried forking the repo and printing the runtimeType to check what is going on but I can't get it to print anything.
