### ISSUE TITLE
Helper classes not compatible with client.create(..) 

### ISSUE THREAD

**Issue by RageshAntony** [comigor/artemis#222]
**Bug description**
Helper classes generated or not

**Specs**
Artemis version: 6.12.3-beta.2

  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
      - lib/graphql/schema.graphql
    builders:
      artemis:
        options:
          generate_helpers: true
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/*.graphql
              output: lib/graphql_api.dart
          scalar_mapping:
            - graphql_type: MongoID
              dart_type: String
            - graphql_type: Date
              dart_type: DateTime
          
          
```

Why helper class is not compatible in with client.execute() params 

My Code :
```
    final client = ArtemisClient('http://192.168.31.107:8000/graphql');
    final catmany = CategoryMany$Query();
    final response = await client.execute(catmany);

But I am getting error : 

The argument type 'CategoryMany$Query' can't be assigned to the parameter type 'GraphQLQuery<dynamic, JsonSerializable>'.
```

What is this error ? pls help me
