### ISSUE TITLE
Unknown definition type

### ISSUE THREAD

**Issue by FickleLife** [comigor/artemis#232]
**Bug description**
I just tried to build my types and got an error: 

```
Exception: Schema `lib/graphql/schema/xx.schema.graphql` was not found or doesn't have a proper format!
Make sure the file exists and you've typed it correctly on build.yaml.
Error on line 660, column 3 of lib/graphql/schema/xx.schema.graphql: Unknown definition type 'RefStatusModeration'
    ╷
660 │   RefStatusModeration: RefStatusModeration!
    │   ^^^^^^^^^^^^^^^^^^^
    ╵
```

The type is in the schema: 
```
# columns and relationships of "RefStatusModeration"
type RefStatusModeration {
  comment: String!
  status: String!
}
```

This has been working fine before. I have not changed the version of `gq` which generates the schema from introspection.   I did update all packages to their latest versions but have since rolled back to a known good from version control and this issue still presents. 

Looking at the build verbose output it seems to error here https://github.com/comigor/artemis/blob/119ea63c3a5b79fc5bda7c423e6f88ff9bdd6b46/lib/builder.dart#L130

Any clues why generation has stopped suddenly? 

**Specs**
Artemis version: I was on `^6.12.3-beta.2`, I've just tried `6.15.1-beta.1` and went all the way back a few random versions to `^6.7.2-beta.1`  
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
    builders:
      json_serializable:
        options:
          include_if_null: false
      artemis:
        options:
          fragments_glob: lib/graphql/data/fragments/*.graphql
          schema_mapping:
            - schema: lib/graphql/schema/koalaroo.schema.graphql
              queries_glob: lib/graphql/data/{mutations,queries,subscriptions}/**.graphql
              output: lib/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
          scalar_mapping:
            - graphql_type: timestamptz
              custom_parser_import: 'package:strayan_app/services/artemis_timeconvert.dart'
              dart_type: DateTime
            - graphql_type: float8
              custom_parser_import: 'package:strayan_app/services/artemis_timeconvert.dart'
              dart_type: double
            - graphql_type: numeric
              dart_type: double
            - graphql_type: _int4
              dart_type: int
            - graphql_type: jsonb
              custom_parser_import: 'package:strayan_app/services/artemis_timeconvert.dart'
              dart_type: dynamic
            - graphql_type: HexColor
              dart_type: String
            - graphql_type: Dimension
              dart_type: int
            - graphql_type: ImageFormat
              dart_type: String
            - graphql_type: Quality
              dart_type: String
            - graphql_type: ImageResizeFocus
              dart_type: String
            - graphql_type: ImageResizeStrategy
              dart_type: String
            - graphql_type: Circle
              dart_type: String
            - graphql_type: Rectangle
              dart_type: String
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: JSON
              dart_type: dynamic
            - graphql_type: json
              dart_type: dynamic

```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
https://gist.github.com/FickleLife/3fcba288f68d1799eba43f3eb7bed881
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
https://gist.github.com/FickleLife/e4f2350384b6d3a2c6dbc2e22561104d 
```
</details>
