### ISSUE TITLE
I can not use custom scalar importing Dart libraries...

### ISSUE THREAD

**Issue by gbmarcos** [comigor/artemis#237]
I have a build.yaml that contain it:

```
 targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          generate_helpers: true
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/graphql/graphql_api.dart         
          scalar_mapping:
            - graphql_type: Date
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: Time
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: UUID
              dart_type: String
            - graphql_type: ID
              dart_type: String
            - graphql_type: Upload
              dart_type: 
                name: MultipartFile
                imports:
                  -  'package:http/http.dart'
```

but when I execute `flutter pub run build_runner build` it thow `Invalid json: {name: MultipartFile, imports: [package:http/http.dart]}`

**Comment by vasilich6107** [comment]
I have this code working without any problems

```
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - rh.schema.graphql
    builders:
      artemis:
        options:
#          custom_parser_import: 'package:graphbrainz_example/coercers.dart'
          scalar_mapping:
            - graphql_type: Upload
              custom_parser_import: 'package:running_hours/helpers/artemis.dart'
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'
```
