### ISSUE TITLE
Looking for a scalar_mapping from JSON to anything that works

### ISSUE THREAD

**Issue by michael-woolsey** [comigor/artemis#265]
## Description
I am feeling like an idiot right now as I simply cannot figure out how to convert a GraphQL JSON field to anything that I can work with in my Artemis object.  

I've tried:

1. scalar_mapping from JSON to `dart_type: String`, this allows me to build the Artemis objects and the application compiles but at runtime it crashes on my `_query.parse(result.data)` with a `type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String' in type cast` error.  I believe that this is because the object `result.data` has already converted the String to a Map internally and cannot convert/cast that back to a String.
2. scalar_mapping from JSON to `dart_type: Map<String, dynamic>`, this allows me to build the Artemis objects, but at application compile time I get the error `Error: Type 'Dynamic' not found.  Map<String, Dynamic> data;`.  I am assuming that this is due to the comma and that it cannot handle generics like this.
3. scalar_mapping from JSON to `dart_type: dynamic` with a `custom_parser_import`, this allows me to build the Artemis objects but at application compile time I get the following error `Error: 'Kw$dynamic' isn't a type.  Kw$dynamic data;`  This one I have no idea what else I could try. 
```
dynamic fromGraphQLJsonToDartKw$dynamic(String value) => json.decode(value ?? '');
String fromDartKw$dynamicToGraphQLJson(dynamic value) => json.encode(value ?? '');
```
4. I even tried with no `scaler_mapping` for JSON but then I get the following error when building the Artemis objects.  `Your schema file contains "JSON" scalar, but this scalar is not configured on build.yaml!` Which is to be expected, but I had to try.

The only thing I can think of is to stop using the `_query.parse()` or change the backend data type from `JSON` to `String` but neither of those options are ideal.  

Is this possible to do or are we trying to do something outside of the scope of Artemis?

Thank you,
Michael

## Specs
Artemis version: 6.18.4
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/artemis/graphql_api.dart
              schema: schema.graphql
              queries_glob: graphql/**/*.graphql
          scalar_mapping:
            - graphql_type: Datetime
              dart_type: DateTime
              custom_parser_import: "package:phyla/graphql/parsers.dart"
            - graphql_type: UUID
              dart_type: String
            - graphql_type: JSON
              dart_type: dynamic
              custom_parser_import: "package:phyla/graphql/parsers.dart"
            - graphql_type: BigFloat
              dart_type: double

```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
$ flutter pub run build_runner build --delete-conflicting-outputs --verbose
[  +91 ms] executing: [C:\Development\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] executing: [C:\Development\flutter/] git tag --points-at HEAD
[  +44 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.6
[   +8 ms] executing: [C:\Development\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}       
[        ] origin/stable
[        ] executing: [C:\Development\flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [C:\Development\flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +45 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +22 ms] Using C:\Development\flutter\.pub-cache for the pub cache.
[        ] executing: C:\Development\flutter\bin\cache\dart-sdk\bin\pub.bat run build_runner build --delete-conflicting-outputs --verbose
[INFO] Generating build script...
[INFO] Generating build script completed, took 328ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 73ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 435ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 21ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 63ms

[INFO] Build:Succeeded after 91ms with 0 outputs (0 actions)

[+3158 ms] "flutter run" took 3,230ms.
[ +126 ms] ensureAnalyticsSent: 118ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
# If possible, please paste your GraphQL schema file,
# or a minimum reproducible schema of the bug.
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql 
query UserLibrary {
  currentUser {
    library {
      nodes {
        name
        resourceTopics {
          nodes {
            resource {
              data
            }
          }
        }
      }
    }
  }
}
```
</details>

**Comment by comigor** [comment]
Hi @michael-woolsey!

Well, one thing that I thought now is that artemis may be converting all `dart_type` types to CamelCase, so `dynamic` is being converted to `Dynamic`.

Just for curiosity, what happens if you define `dart_type` as `Map<String, Object>`?

**Comment by michael-woolsey** [comment]
Hello @comigor!

Unfortunately when I change my dart_type to:
```            
- graphql_type: JSON
  dart_type: Map<String, Object>
```

Artemis builds the objects, and the application compiles, however at runtime when I try to `final query = _query.parse(result.data);` I get the following error `type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast`.

**Comment by comigor** [comment]
Got you. Thanks, I'll take a look!

**Comment by comigor** [comment]
There's some naming issues on artemis but me and @michael-golfi talked on DM and thought in a workaround (for now): creating an wrapping class for the Json scalar.

`build.yaml`
```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          scalar_mapping:
          - graphql_type: JSON
            dart_type: Json
            custom_parser_import: 'package:your_package/src/custom_parser.dart'
```

`custom_parser.dart`
```dart
class Json {
  const Json(this.value);

  final Map<String, dynamic> value;
}

Json fromGraphQLJsonToDartJson(dynamic data) {
  return Json(Map<String, dynamic>.from(data as Map<dynamic, dynamic>));
}

dynamic fromDartJsonToGraphQLJson(Json data) => data.value;
```
