### ISSUE TITLE
Nullable scalar_mapping types 

### ISSUE THREAD

**Issue by michael-woolsey** [comigor/artemis#293]
## Bug description
I'm getting the following issue when attempting to generate my objects.

`Error with '@JsonKey' on 'occurrence'. The 'fromJson' function 'fromGraphQLDatetimeToDartDateTime' return type 'DateTime?' is not compatible with field type 'DateTime'.`

This seems to be occurring due to my parsing of datetime from postgres to dart:
```
DateTime? fromGraphQLDatetimeToDartDateTime(String? date) => date == null ? null : DateTime.parse(date).toLocal();
String? fromDartDateTimeToGraphQLDatetime(DateTime? date) => date?.toUtc().toIso8601String();
```

I hope I'm just missing something obvious, but I want to be able to pass nullable date values back and forth from my database, any idea what I'm doing wrong?

I tried adding the ? to the build.yaml and of course that doesn't work, but I had to try.

## Specs
Artemis version: 7.0.0-beta.3
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
      - schema.graphql
      - $package$
    builders:
      artemis:
        options:
          fragments_glob: lib/graphql/fragments/*.graphql
          schema_mapping:
            - output: lib/graphql/artemis/resolvers.dart
              schema: schema.graphql
              queries_glob: lib/graphql/resolvers/**/*.graphql
          scalar_mapping:
            - graphql_type: Datetime
              dart_type: DateTime
              custom_parser_import: "package:phyla/graphql/parsers.dart"
            - graphql_type: UUID
              dart_type: String
            - graphql_type: JSON
              dart_type: Json
              custom_parser_import: "package:phyla/graphql/parsers.dart"
            - graphql_type: BigFloat
              dart_type: double
              custom_parser_import: "package:phyla/graphql/parsers.dart"
            - graphql_type: Cursor
              dart_type: String
            - graphql_type: Date
              dart_type: DateTime
              custom_parser_import: "package:phyla/graphql/parsers.dart"

```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash

[FINE] json_serializable:json_serializable on lib/graphql/artemis/resolvers.graphql.dart:Running JsonSerializableGenerator - 1 of 2
[SEVERE] json_serializable:json_serializable on lib/graphql/artemis/resolvers.graphql.dart:

Error with `@JsonKey` on `occurrence`. The `fromJson` function `fromGraphQLDatetimeToDartDateTime` return type `DateTime?` is not compatible with field type `DateTime`.
package:phyla/graphql/artemis/resolvers.graphql.dart:462:17
    ╷
462 │   late DateTime occurrence;
    │                 ^^^^^^^^^^
    ╵
package:json_serializable/src/utils.dart 56:5                         throwUnsupported
package:json_serializable/src/type_helper_ctx.dart 138:7              _convertData
package:json_serializable/src/type_helper_ctx.dart 99:26              new _ConvertPair
package:json_serializable/src/type_helper_ctx.dart 41:40              TypeHelperCtx._pairFromContext
package:json_serializable/src/type_helper_ctx.dart 39:46              TypeHelperCtx.deserializeConvertData
package:json_serializable/src/type_helpers/convert_helper.dart 52:34  ConvertHelper.deserialize
package:json_serializable/src/type_helper_ctx.dart 64:31              TypeHelperCtx.deserialize.<fn>
dart:core                                                             Iterable.firstWhere
package:json_serializable/src/type_helper_ctx.dart 77:46              TypeHelperCtx._run
package:json_serializable/src/type_helper_ctx.dart 61:7               TypeHelperCtx.deserialize
package:json_serializable/src/decode_helper.dart 192:14               DecodeHelper._deserializeForField
package:json_serializable/src/decode_helper.dart 53:9                 DecodeHelper.createFactory.deserializeFun
package:json_serializable/src/decode_helper.dart 120:33               DecodeHelper.createFactory
package:json_serializable/src/generator_helper.dart 85:28             GeneratorHelper.generate.sync_op

[INFO] Build:Running build completed, took 6.1s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 45ms

[SEVERE] Build:
Failed after 6.1s
[+8980 ms] "flutter run" took 9,099ms.
[   +6 ms] pub finished with exit code 1
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:364:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:238:5)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +180 ms] ensureAnalyticsSent: 172ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
# If possible, please paste your GraphQL schema file,
# or a minimum reproducible schema of the bug.
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
# If possible, please paste your GraphQL query file,
# or a minimum reproducible query of the bug.
```
</details>

**Comment by michael-woolsey** [comment]
Looking more into it, this appears to getting confused between DateTime that are nullable and DateTimes that are not nullable, as our database contains both.

I'll continuing searching and let you know if I find anything more.

**Comment by comigor** [comment]
Hey @michael-woolsey,
Non-nullable types should be compatible with nullable ones, so what happens if you only declare non-nullable versions?
```dart
DateTime fromGraphQLDatetimeToDartDateTime(String date) => DateTime.parse(date).toLocal();
String fromDartDateTimeToGraphQLDatetime(DateTime date) => date.toUtc().toIso8601String();
```

**Comment by michael-woolsey** [comment]
Hello @comigor,

If I switch to non-nullable versions I get the same type of error for a different field.

So basically my database has various DateTime fields that are non-nullable and various ones that are nullable.  I believe the issue is that my scaler parsing doesn't know which one to use as I can only return nullable or non-nullable with a single function name.

As you can see, the `?` has swapped places in this message:
Original error:
`Error with '@JsonKey' on 'occurrence'. The 'fromJson' function 'fromGraphQLDatetimeToDartDateTime' return type 'DateTime?' is not compatible with field type 'DateTime'.`

New error:
`Error with '@JsonKey' on 'stopDate'. The 'toJson' function 'fromDartDateTimeToGraphQLDatetime' argument type 'DateTime' is not compatible with field type 'DateTime?'.`

Hopefully this make sense?

**Comment by comigor** [comment]
Ooooh, I see! That might be an easy fix, I'll see if I can drop a PR later.

**Comment by comigor** [comment]
@michael-woolsey @michael-golfi
That's actually something that came up on `json_serializable`: https://github.com/google/json_serializable.dart/issues/822

Testing an example locally, I've found the following works for artemis (having arguments nullable, and return type non-null):
```dart
DateTime fromGraphQLDateTimeToDartDateTime(String? date) => date == null ? DateTime.now() : DateTime.parse(date).toLocal();
String fromDartDateTimeToGraphQLDateTime(DateTime? date) => (date ?? DateTime.now()).toUtc().toIso8601String();
```

However, by using this solution you'd have to set a default return for when argument is null, which is not good.

So the only way I see to fix this (without any change from json_serializable side) would be to have different coercers for nullable/non-null types:
```dart
DateTime fromGraphQLDateTimeToDartDateTime(String date) => DateTime.parse(date).toLocal();
String fromDartDateTimeToGraphQLDateTime(DateTime date) => date.toUtc().toIso8601String();

DateTime? fromGraphQLDateTimeToDartDateTimeNullable(String? date) => date == null ? null : DateTime.parse(date).toLocal();
String? fromDartDateTimeToGraphQLDateTimeNullable(DateTime? date) => date?.toUtc().toIso8601String();
```

**Comment by michael-golfi** [comment]
Thanks @comigor!

I don't think setting a default would be all that bad... Although just to confirm, does the second solution work with the current latest beta?

**Comment by comigor** [comment]
The first one does. The second is something that maybe Artemis could provide, if it would be necessary.

But I'm leaning towards waiting for json_serializable to do something about the issue I've linked above.

**Comment by michael-woolsey** [comment]
Hello @comigor 

Since the latest changes appear to be merged into master but not published yet, I tried to use the master branch of `json_serializable` by doing:
```
  json_serializable:
    git:
      url: https://github.com/google/json_serializable.dart.git
      path: json_serializable/
      ref: master

  json_annotation:
    git:
      url: https://github.com/google/json_serializable.dart.git
      path: json_annotation/
      ref: master
```

However I get the error `Because [app] depends on json_serializable from git which depends on json_annotation >=4.1.0 <4.2.0, json_annotation from hosted is required.` which I believe is telling me they disallow people from doing this as stated `from hosted is required.`.

I understand that you're going to wait for Google to deal with `json_serializable` at this time so we will investigate other alternatives on our side, I just wanted to share what I tried.

Thanks again for your time!
