### ISSUE TITLE
Fragment duplicate generated mixins

### ISSUE THREAD

**Issue by nbourdin** [comigor/artemis#304]
## Bug description
When i use fragment in my queries, the generated mixin are duplicated in each query file 

## Specs
Artemis version: 7.0.0-beta.9
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: graphql/**.fragment.graphql
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/query/event/recommendations.query.graphql
              output: lib/datasource/event/query/recommendations_query.dart
            - schema: schema.graphql
              queries_glob: graphql/query/event/similar_events.query.graphql
              output: lib/datasource/event/query/similar_events_query.dart
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
[INFO] Generating build script...
[INFO] Generating build script completed, took 643ms

[WARNING] The package `epeak` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 185ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 780ms

[INFO] Running build...
[INFO] Running build completed, took 25ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 71ms

[INFO] Succeeded after 107ms with 0 outputs (0 actions)
```
</details>
<details>
<summary>GraphQL fragment:</summary>

```graphql
fragment EventLight on Event {
  _id
  title
  category
  thumbnail
  start_date
  races {
    distance_meter
  }
  location_infos {
    city
    geo {
      coordinates
    }
  }
}
```
</details>

<details>
<summary>GraphQL query1:</summary>

```graphql
query recommendations {
  recommendations(country: "France") {
    title
    events {
      ...EventLight
    }
  }
}
```
</details>

<details>
<summary>Generated code from query 1:</summary>

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND
// @dart = 2.12

import 'package:artemis/artemis.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:equatable/equatable.dart';
import 'package:gql/ast.dart';
part 'recommendations_query.graphql.g.dart';

mixin EventLightMixin {
  @JsonKey(name: '_id')
  late String $id;
  late String title;
  late String category;
  late String thumbnail;
  @JsonKey(name: 'start_date')
  DateTime? startDate;
  late List<EventLightMixin$Race> races;
  @JsonKey(name: 'location_infos')
  late EventLightMixin$LocationInformation locationInfos;
}
...
```
</details>

<details>
<summary>GraphQL query 2:</summary>

```graphql
query similarEvents(
  $where: String!
  $longitude: Float!
  $latitude: Float!
  $radius: Float!
) {
  events(
    area: { longitude: $longitude, latitude: $latitude, radius: $radius }
    page: 0
    pageSize: 15
    whereJsonString: $where
  ) {
    items {
      ...EventLight
    }
  }
}

```
</details>

<details>
<summary>Generated code from query 2:</summary>

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND
// @dart = 2.12

import 'package:artemis/artemis.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:equatable/equatable.dart';
import 'package:gql/ast.dart';
part 'similar_events_query.graphql.g.dart';

mixin EventLightMixin {
  @JsonKey(name: '_id')
  late String $id;
  late String title;
  late String category;
  late String thumbnail;
  @JsonKey(name: 'start_date')
  DateTime? startDate;
  late List<EventLightMixin$Race> races;
  @JsonKey(name: 'location_infos')
  late EventLightMixin$LocationInformation locationInfos;
}
...
```
</details>
