### ISSUE TITLE
Cannot define multiple queries (with fragments) in a single .graphql file

### ISSUE THREAD

**Issue by fpabl0** [comigor/artemis#307]
**Before reporting a bug, please test the beta branch!** 
(Unfortunately I can't test it with the beta branch because it caused a lot of conflicting dependencies problems in my application).

## Bug description
When multiple queries are defining in the same file using fragments, Artemis generate a Query with the Fragment declared twice. That causes this exception at runtime:

<img width="753" alt="Captura de Pantalla 2021-05-10 a la(s) 04 38 24" src="https://user-images.githubusercontent.com/12239342/117639961-1e5c6500-b14a-11eb-95c1-fabaa0469419.png">

Here it is defined twice:
```dart
class GetAllPokemonsQuery
    extends GraphQLQuery<GetAllPokemons$Query, GetAllPokemonsArguments> {
  GetAllPokemonsQuery({this.variables});

  @override
  final DocumentNode document = DocumentNode(definitions: [
    ...
    FragmentDefinitionNode(
        name: NameNode(value: 'pokemonFragment'),
        ...
    ])),
    FragmentDefinitionNode(
        name: NameNode(value: 'pokemonFragment'),
        ...
    ])),
    ...
  ]);
  ...
}
```

## Specs
Artemis version: 6.18.4
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
      - $package$
    builders:
      artemis:
        options:
          fragments_glob: graphql/fragments/fragments.graphql
          schema_mapping:
            - schema: schema.graphql
              naming_scheme: pathedWithFields
              queries_glob: graphql/*.{query,mutation}.graphql
              output: lib/models/graphql/graphql_api.dart
```
</details>
<details>
<summary>Artemis output:</summary>
  
The error occurs at runtime.

</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
type Pokemon {
  number: String
  name: String
}

type Query {
  pokemons(first: Int!): [Pokemon]
  pokemon(name: String!): Pokemon!
}
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
# graphql/fragments/fragments.graphql
fragment pokemonFragment on Pokemon {
  number
  name
}

# graphql/pokemon.query.graphql
query getPokemon($name: String!) {
  pokemon(name: $name) {
    ...pokemonFragment
  }
}

query getAllPokemons($first: Int!) {
  pokemons(first: $first) {
    ...pokemonFragment
  }
}
```
</details>
