### ISSUE TITLE
How to generate Optional type for nullable graphql type?

### ISSUE THREAD

**Issue by edbond** [comigor/artemis#311]
**Before reporting a bug, please test the beta branch!**

I am using beta branch.

## Bug description

GraphQL schema type doesn't ends with !,
when I receive `null` from server parsing fails with:

Unhandled Exception: Unhandled error type 'Null' is not a subtype of type 'String' in type cast occurred

Expected:
```dart
    ..oneDayChange =
        fromGraphQLDecimalToDartdoubleNullable(json['oneDayChange'] as String?)
```

Generated
```dart
    ..oneDayChange =
        fromGraphQLDecimalToDartdoubleNullable(json['oneDayChange'] as String)
```

## Specs
Artemis version: beta
<details>
<summary>build.yaml:</summary>
  
```yaml
# Please paste your `build.yaml` file
targets:
  $default:
    sources:
      - $package$
      - lib/**
      - graphql/**
    builders:
          
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: abc.schema.graphql
              queries_glob: graphql/*.graphql

          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: Decimal
              dart_type: double
              custom_parser_import: 'package:abc/coercers.dart'
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
# Please paste the output of
$ flutter pub run build_runner build --verbose
#or
$ pub run build_runner build --verbose
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
# If possible, please paste your GraphQL schema file,
# or a minimum reproducible schema of the bug.

  oneDayChange: Decimal

```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
# If possible, please paste your GraphQL query file,
# or a minimum reproducible query of the bug.
query Search($query: String!) {
  byPrefix: stocksSearch(symbol_Istartswith: $query, first: 4) {    
    edges {
      node {
        id
        symbol
        name
        oneDayChange
      }
    }
  }
}
```
</details>
