### ISSUE TITLE
use_custom_parser has no effect

### ISSUE THREAD

**Issue by dan-leech** [comigor/artemis#315]
## Bug description
`use_custom_parser: true` has no effect

## Specs
Artemis version: 7.0.0-beta.11
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - $package$
      - lib/**
      - schema.graphql
      - queries/**.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: queries/**.query.graphql
              output: lib/api/graphql_api.dart
          fragments_glob: queries/**.fragment.graphql
          custom_parser_import: 'package:p/infrastructure/graphql_parsers.dart'
          scalar_mapping:
            - graphql_type: Date
              dart_type: DateTime
              custom_parser_import: 'package:p/infrastructure/graphql_parsers.dart' # this woking ok
            - graphql_type: Time
              dart_type: DateTime
              use_custom_parser: true # no effect, uses usual DateTime.parse instead
```
</details>
<details>
<summary>Artemis output:</summary> as usual
