### ISSUE TITLE
Could not generate `fromJson` code for list of custom scalar (ex. MultipartFile)

### ISSUE THREAD

**Issue by fikretsengul** [comigor/artemis#320]
Hello, I am trying to implement Upload type custom scalar with the help of @vasilich6107 s guidance in this issue. (https://github.com/comigor/artemis/issues/118)

But the code generator says:
```
[SEVERE] json_serializable:json_serializable on lib/infrastructure/graphql/graphql_api.graphql.dart (cached):

Could not generate `fromJson` code for `photos` because of type `MultipartFile`.
package:matchubs/infrastructure/graphql/graphql_api.graphql.dart:11554:30
      ╷
11554 │   final List<MultipartFile>? photos;
```

I don't know how to fix this problem. Can anyone help me?

**Comment by vasilich6107** [comment]
Show me your code.
What did you code basing on this example?
https://github.com/comigor/artemis/issues/118#issuecomment-623112131

**Comment by darmie** [comment]
@fikretsengul  look at my response on the other related issue here
https://github.com/comigor/artemis/issues/118#issuecomment-857591213

**Comment by fikretsengul** [comment]
Thank you so much for the attention and fast response. @vasilich6107 and @darmie My configurations are:

Flutter version: Flutter 2.2.0 • channel stable •
Dart version: Dart SDK version: 2.13.0 (stable)
Flutter environment in pubspec.yaml: sdk: ">=2.12.2 <3.0.0"

> I'm using flutter with null-safety. I've tried:

```
flutter clean
flutter pub get
flutter packages pub run build_runner watch --delete-conflicting-outputs
```

> update_photos.graphql

```
mutation uploadPhotos($userId: String!, $photos: [Upload!]) {
  uploadPhotos(userId: $userId, photos: $photos)
}
```

> schema.graphql

```
scalar Upload
type Mutation {
        uploadPhotos(userId: String!, photos: [Upload!]): [String]!
}
```

> upload_scalar.dart

```
import 'package:http/http.dart';

MultipartFile fromGraphQLUploadToDartMultipartFile(MultipartFile file) => file;
MultipartFile fromDartMultipartFileToGraphQLUpload(MultipartFile file) => file;
List<MultipartFile> fromGraphQLListUploadToDartListMultipartFile(
        List<MultipartFile> files) =>
    files;
List<MultipartFile> fromDartListMultipartFileToGraphQLListUpload(
        List<MultipartFile> files) =>
    files;
```

> build.yaml

```
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/infrastructure/graphql/schema.graphql
              naming_scheme: pathedWithFields
              queries_glob: lib/infrastructure/graphql/queries/**.graphql
              output: lib/infrastructure/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: DateTime
              custom_parser_import: "lib/infrastructure/graphql/scalars/datetime_scalar.dart"
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: Upload
              custom_parser_import: "lib/infrastructure/graphql/scalars/upload_scalar.dart"
              dart_type:
                name: MultipartFile
                imports:
                  - "package:http/http.dart"
              use_custom_parser: true
```

> The status of graphql_api.graphql.dart

https://imgur.com/vfeUdNk.png

What's more interesting there are other problems related to various things in graphql_api.graphql.dart, but the code generator compiles without any problems.

> The status of vscode output

https://imgur.com/QDbveaV.png

> datetime_scalar.dart

```
import 'package:intl/intl.dart';

final dateFormatter = DateFormat('yyyy-MM-dd');
final timeFormatter = DateFormat('HH:mm:ss');

DateTime fromGraphQLDateToDartDateTime(String date) => DateTime.parse(date);
String fromDartDateTimeToGraphQLDate(DateTime date) =>
    dateFormatter.format(date);
DateTime fromGraphQLTimeToDartDateTime(String time) =>
    DateTime.parse('1970-01-01T${time}Z');
String fromDartDateTimeToGraphQLTime(DateTime date) =>
    timeFormatter.format(date);
```

> The status of graphql_api.graphql.dart

https://imgur.com/f5mQo0V.png

> The status of code generator

https://imgur.com/qK7gbyX.png
