### ISSUE TITLE
Errors when using v2.13 of the sdk

### ISSUE THREAD

**Issue by johannbuscail** [comigor/artemis#338]
**Before reporting a bug, please test the beta branch!**

## Bug description
I'm using the version 2.13.0 for the SDK because it is required to use type aliases on variables
When I generate the dart file from my flutter queries, I get this error on VSCode and while running the app:
```error
Parts must have exactly the same language version override as the library. dart(inconsistent_language_version_override)
```
and
```
Target of URI hasn't been generated: 'graphql.graphql.g.dart'.
Try running the generator that will generate the file referenced by the URI. dart(uri_has_not_been_generated)
```
**I think all of those errors happen because the `.g.dart` file isn't generated**

## Specs
Artemis version: `^7.1.0-beta.0`
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/api/graphql/generated/graphql.dart
              schema: lib/api/graphql/schema.graphql
              queries_glob: lib/api/graphql/{queries,mutations}/**.graphql
          scalar_mapping:
            - graphql_type: UUID
              dart_type: String

            - graphql_type: DateTime
              dart_type: DateTime

            - graphql_type: JWT
              dart_type: String
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
[WARNING] The package does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 144ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 720ms

[INFO] Running build...
[INFO] Running build completed, took 785ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 71ms

[INFO] Succeeded after 875ms with 2 outputs (1 actions)

```
</details>
<details>
<summary>GraphQL schema: (simplified for the example)</summary>

```graphql
"""
The javascript `Date` as string. Type represents date and time as the ISO Date string.
"""
scalar DateTime

"""
A field whose value is a generic Universally Unique Identifier: https://en.wikipedia.org/wiki/Universally_unique_identifier.
"""
scalar UUID

type LoggedInUser {
  uuid: UUID!
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
  username: String!
}

type Mutation {
  login(
    """The username of someone"""
    identifier: String!
    password: String!
  ): LoggedInUser!
}


```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
mutation Login($identifier: String, $password: String){
  login(identifier: $identifier, password: $password) {
    uuid
    username
  }
}

```
</details>

**Comment by vasilich6107** [comment]
Where are your errors come from?
I do not see any errors in atremis output

**Comment by johannbuscail** [comment]
The errors come when I run the app and VSCode shows them to.

**Comment by vasilich6107** [comment]
I just finished migration of my test project to null safety with latest Dart SDK and artemis
https://github.com/artflutter/graphql_toolchain

I can build and run it without any issues

**Comment by vasilich6107** [comment]
It seems that there is no `.g.dart` it causes those errors

**Comment by johannbuscail** [comment]
> It seems that there is no .g.dart it causes those errors

Yes exactly. Do you get the same problem ?

**Comment by vasilich6107** [comment]
Nope
I just accidentally noticed it while developing a feature

**Comment by johannbuscail** [comment]
Is there a specific command that I might have forgotten to generate the `.g.dart` ?
I have followed step by step the doc.
Could you try by enabling this:
```yaml
analyzer:
  enable-experiment:
    - nonfunction-type-aliases
```
In the `analysis_options.yaml` file (it's the only thing diferent)
