### ISSUE TITLE
Having a property called "override" causes built to fail.

### ISSUE THREAD

**Issue by tylergets** [comigor/artemis#340]
**Before reporting a bug, please test the beta branch!**

## Bug description
If you have a graphql property called override on any of your objects, artemis will fail to generate the code.

## Specs
Artemis version: [e.g. 7.0.0-beta.11]
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/**/*.gql
              output: lib/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
[SEVERE] json_serializable:json_serializable on lib/graphql/graphql_api.graphql.dart:

line 1, column 10766 of package:test/graphql/graphql_api.graphql.dart: Could not resolve annotation for `List<Object?> get props`.
  ╷
1 │ @override
  │ ^^^^^^^^^
  ╵
[INFO] Running build completed, took 5.6s
```
</details>
