### ISSUE TITLE
Fragments: The superclass, '<name>FragmentMixin', has no unnamed constructor that takes no arguments

### ISSUE THREAD

**Issue by tuanvugoodmoney** [comigor/artemis#346]
**Before reporting a bug, please test the beta branch!**

## Bug description
I have a fragment that with direct fields except __typename and a union. The fragment and query is generated successfully, but when I write a unit test, I get the following errors while loading the unit tests. The query and fragment runs successfully on Apollo Graph explorer.

### Errors
```
Failed to load "test/graphql_gateway_client_inquiry_test.dart":
lib/src/graphql/graphql.graphql.dart:3251:7: Error: The superclass, 'InquiryFragmentMixin', has no unnamed constructor that takes no arguments.
class InquiryFragmentMixin$Inquiry extends InquiryFragmentMixin
      ^
lib/src/graphql/graphql.graphql.dart:3272:7: Error: The superclass, 'InquiryFragmentMixin', has no unnamed constructor that takes no arguments.
class InquiryFragmentMixin$InquiryNotFoundError extends InquiryFragmentMixin
      ^
lib/src/graphql/graphql.graphql.dart:3290:7: Error: The superclass, 'InquiryFragmentMixin', has no unnamed constructor that takes no arguments.
class InquiryFragmentMixin$ServiceUnavailableError extends InquiryFragmentMixin
      ^
lib/src/graphql/graphql.graphql.dart:3308:7: Error: The superclass, 'InquiryFragmentMixin', has no unnamed constructor that takes no arguments.
class InquiryFragmentMixin$InquiryResumeFailedError extends InquiryFragmentMixin

```

## Specs
Artemis version: 7.1.1-beta.1
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/src/graphql/**
      - lib/src/graphql/schema.graphql
  graphql_gateway:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - public_member_api_docs
            - lines_longer_than_80_chars
            - constant_identifier_names
      artemis:
        options:
          fragments_glob: lib/src/graphql/fragments/*.fragment.graphql
          schema_mapping:
            - schema: lib/src/graphql/schema.graphql
              queries_glob: lib/src/graphql/queries/**.graphql
              output: lib/src/graphql/graphql.dart
          scalar_mapping:
            - graphql_type: PhoneNumber
              dart_type: String
            - graphql_type: EmailAddress
              dart_type: String
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: PostalCode
              dart_type: String
      json_serializable:
        options:
          include_if_null: false

```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
flutter pub run build_runner build --verbose
[ +119 ms] executing: sysctl hw.optional.arm64
[  +24 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +13 ms] executing: [/Applications/Flutter/beta/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] executing: [/Applications/Flutter/beta/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[ +198 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[   +7 ms] executing: [/Applications/Flutter/beta/] git rev-parse --abbrev-ref --symbolic @{u}
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Applications/Flutter/beta/] git ls-remote --get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +133 ms] executing: [/Applications/Flutter/beta/] git rev-parse --abbrev-ref HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +9 ms] executing: sw_vers -productName
[  +21 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +21 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.4
[        ] executing: sw_vers -buildVersion
[  +24 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20F71
[  +97 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +173 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +19 ms] executing: /Applications/Flutter/beta/bin/cache/dart-sdk/bin/pub run build_runner build --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 650ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 80ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 498ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 20ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 44ms

[INFO] Build:Succeeded after 78ms with 0 outputs (0 actions)

[+3945 ms] "flutter run" took 4,186ms.
[   +5 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
union InquiryResult = Inquiry | InquiryNotFoundError | InquiryResumeFailedError | ServiceUnavailableError
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
fragment inquiryResultFragment on InquiryResult {
  __typename
  ... on Inquiry {
    id
    status
    accessToken
  }
  ... on InquiryNotFoundError {
    message
  }
  ... on ServiceUnavailableError {
    message
  }
  ... on InquiryResumeFailedError {
    message
  }
}


query getInquiryById($inquiryById: ID!) {
  user {
    inquiryBy(id: $inquiryById) {
      ...inquiryResultFragment
    }
  }
}

```
</details>
