### ISSUE TITLE
Deeply nested fragments not working

### ISSUE THREAD

**Issue by tk2232** [comigor/artemis#361]
## Bug description
Deeply nested fragments not working. 

If I run ChatMessages with graphql the authors in result are null

```dart
QueryOptions getMessageOptions(String id) {
    final arguments = ChatMessagesArguments(chatId: id);
    return QueryOptions(
        document: ChatMessagesQuery(variables: arguments).document,
        variables: arguments.toJson());
  }
```

```GraphQL
fragment PublicUserFragment on UserPublic {
    objectId
    photoURL
    username
    gender
}


fragment ChatMessagesFragment on ChatMessageEdge {
    node {
        ...ChatMessageFragment
    }
}

fragment ChatMessageFragment on ChatMessage {
    __typename
    objectId
    createdAt
    updatedAt
    chat {
        objectId
    }
    author {
        ...PublicUserFragment
    }
    message
    offlineId
}

query ChatMessages($chatId: ID!) {
    chatMessages(where: { chat: { have: { objectId: { equalTo: $chatId } } } }) {
        edges {
            node {
                ...ChatMessageFragment
            }
        }
    }
}
```

## Specs
Artemis version:  artemis: ^7.2.6-beta
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
    builders:
      artemis:
        options:
          fragments_glob: lib/graphql/fragments/*.graphql
          schema_mapping:
            - schema: lib/graphql/test.schema.graphql
              queries_glob: lib/graphql/queries/**.graphql
              output: lib/graphql/graphql_api.graphql.dart
          scalar_mapping:
            - graphql_type: Date
              custom_parser_import: 'package:test/graphql/coercers.dart'
              dart_type: DateTime
```
