### ISSUE TITLE
Multiple Schema Files within One Mapping?

### ISSUE THREAD

**Issue by cody1024d** [comigor/artemis#362]
Hello,

Quick question --- does Artemis support multiple schema files within one "mapping"?  Hoping to do something like this in the YAML file:

```yaml
schema_mapping:
            - output: lib/service/graphql/types.graphql.dart
              schema: assets/graphql/{aws_appsync,schema}.graphql
              queries_glob: assets/graphql/types/{queries,mutations}/**.graphql
              fragments_glob: assets/graphql/types/fragments/**.graphql
```

This use-case comes up because we have one file that is auto-generated from our backend, `schema.graphql`. However, the second contains some Scalar Types that AWS expects to be included, but however are not the standard GraphQL scalar types (such as AWSDate, AWSURL, etc.). 

Currently, every time a new `schema.graphql` is generated, I would have to manually append the contents of the second schema file (otherwise Artemis doesn't know what those custom types are). I believe supporting 2 schema files in a single mapping would solve this.

I've tried the above, and Artemis doesn't seem to like it.
