### ISSUE TITLE
Undefined name '$$typename' when nesting unions

### ISSUE THREAD

**Issue by kazuyaseki** [comigor/artemis#369]
## Bug description
I have a following schema.

```graphql
type Query {
  home(input: HomeQueryInput!): HomeResult!
}

union HomeItem = Hoge | Fuga

type HomePayload {
  home: [HomeItem!]!
}

union HomeResult = HomePayload | NotFound | ValidationError
```

when I generate with artemis

```dart
@JsonSerializable(explicitToJson: true)
class Home$Query$HomeResult$HomePayload$HomeItem extends JsonSerializable
    with EquatableMixin {
  Home$Query$HomeResult$HomePayload$HomeItem();

  factory Home$Query$HomeResult$HomePayload$HomeItem.fromJson(
      Map<String, dynamic> json) {
    switch (json['__typename'].toString()) {
      case r'Hoge':
        return Home$Query$HomeResult$HomePayload$HomeItem$Hoge.fromJson(
            json);
      case r'Fuga':
        return Home$Query$HomeResult$HomePayload$HomeItem$Fuga
            .fromJson(json);
      default:
    }
    return _$Home$Query$HomeResult$HomePayload$HomeItemFromJson(json);
  }

  @override
  List<Object?> get props => [];
  @override
  Map<String, dynamic> toJson() {
    switch ($$typename) { // this line it produces error `Undefined name '$$typename'`
      case r'Hoge':
        return (this as Home$Query$HomeResult$HomePayload$HomeItem$Hoge)
            .toJson();
      case r'Fuga':
        return (this
                as Home$Query$HomeResult$HomePayload$HomeItem$Fuga)
            .toJson();
      default:
    }
    return _$Home$Query$HomeResult$HomePayload$HomeItemToJson(this);
  }
}
```

which causes error `Undefined name '$$typename'`
other query that's using Union is fine, so I guess it might be caused by nesting unions

## Specs
Artemis version: 7.2.2-beta
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/**/**.graphql
              output: lib/service/graphql_client_service/generated/graphql_api.dart
          scalar_mapping:
            - custom_parser_import: package:pocket_musubi_native/service/graphql_client_service/custom_scalar_parser.dart
              graphql_type: AWSDate
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: AWSDateTime
              dart_type: DateTime
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
# Please paste the output of
$ flutter pub run build_runner build --verbose
#or
$ pub run build_runner build --verbose
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
type Hoge {
  id
}

type Fuga {
  id
}

type Query {
  home: HomeResult!
}

union HomeItem = Hoge | Fuga

type HomePayload {
  home: [HomeItem!]!
}

union HomeResult = HomePayload | NotFound | ValidationError
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
# If possible, please paste your GraphQL query file,
# or a minimum reproducible query of the bug.
```
</details>
