### ISSUE TITLE
Missing enum type when create .dart file

### ISSUE THREAD

**Issue by Thong-Tran** [comigor/artemis#37]
I create by file graphql with content:

```graphql
query AllUsers($filter: FilterInput, $limit: Int, $nextToken: String) {
  allUsers(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      Attributes {
        Name
        Value
      }
      Username
    }
    nextToken
  }
}
```

with file [schema.json](https://github.com/comigor/artemis/files/3689659/schema.zip) create from **appsync aws**. Everything worked fine and created .dart files but it didn't include enum type.

Has it been supported since the beginning or is this a bug?

**Comment by comigor** [comment]
Hello @Thong-Tran, how are you doing?
I'm not familiar with this schema, is `FilterInput` an enum?
Yes, it's probably a bug, enums are supposed to work. I'll take a look as soon as possible.

**Comment by Thong-Tran** [comment]
> is FilterInput an enum?

No, attributes of `FilterInput` is enum, like this:

```graphql
enum SearchableAttribute {
  email
  name
  username
}

enum SearchableType {
  BEGIN_WITH
  EXTRACTLY
}


input FilterInput {
  Name: SearchableAttribute!
  Type: SearchableType!
  Value: String!
}
```

And with config

```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/services/graphql_api.dart
              schema: lib/schema.json
              queries_glob: lib/allUsers.query.graphql
```
