### ISSUE TITLE
Installing 6.18.4 artemis

### ISSUE THREAD

**Issue by MichalNemec** [comigor/artemis#404]
Tried   artemis: 7.2.3-beta which works, but fails on:
```
[WARNING] ../../.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.3.0-alpha+1635885531709/lib/src/ast.dart:618:12: Error: A non-null value must be returned since the return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('../../.pub-cache/hosted/pub.dartlang.org/code_builder-4.3.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Precompiling build script... completed, took 649ms
```

## Bug description
Cannot install 6.18.4 artemis or any version.

## Specs
Artemis version: 6.18.4
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/api/schema/schema.graphql
              queries_glob: lib/api/queries.graphql
              output: lib/api/queries.dart
              naming_scheme: simple

```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
cannot be installed
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
cannot be installed
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
cannot be installed
```
</details>

```
Running "flutter pub get" in mobileapp...                       
Because no versions of json_serializable match >6.5.4 <7.0.0 and json_serializable 6.5.4 depends on source_gen ^1.0.0, json_serializable ^6.5.4 requires source_gen ^1.0.0.
And because artemis >=6.17.2 <7.0.0-beta.2 depends on source_gen ^0.9.10+1, json_serializable ^6.5.4 is incompatible with artemis >=6.17.2 <7.0.0-beta.2.
So, because mobileapp depends on both artemis ^6.18.4 and json_serializable ^6.5.4, version solving failed.
pub get failed (1; So, because mobileapp depends on both artemis ^6.18.4 and json_serializable ^6.5.4, version solving failed.)
exit code 1
```

```
dependencies:
  adaptive_action_sheet: ^2.0.2
  animations: ^2.0.7
  badges: ^2.0.3
  cached_network_image: ^3.2.2
  calendar_timeline: ^1.0.5
  catcher: ^0.7.0
  collection: ^1.16.0
  connectivity_plus: ^1.4.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  custom_image_crop: ^0.0.4
  custom_refresh_indicator: ^2.0.0
  easy_localization: ^3.0.1
  expandable_page_view: ^1.0.17
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_dialogs: ^3.0.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_mailer: ^2.0.1
  flutter_markdown: ^0.6.12
  flutter_reorderable_list: ^1.2.0
  flutter_riverpod: ^2.1.1
  flutter_switch: ^0.3.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_typeahead: ^4.1.1
  freezed_annotation: ^2.2.0
  graphql: ^5.0.0
  graphql_flutter: ^5.0.0
  image_picker: ^0.8.6
  json_annotation: ^4.7.0
  lottie: ^1.4.3
  nhost_flutter_auth: ^2.0.4
  nhost_flutter_graphql: ^2.1.0
  nhost_graphql_adapter: ^2.0.4
  nhost_sdk: ^3.0.4
  numeral: ^2.0.1
  palette_generator: ^0.3.3+2
  percent_indicator: ^4.2.2
  reactive_forms: ^14.1.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  swipe_image_gallery: ^0.8.0
  timeago: ^3.3.0
  uipickers: ^0.0.9
  url_launcher: ^6.1.6
  zoom_tap_animation: ^1.1.0

dependency_overrides: #temporary fix before nhost_flutter_graphql is updated to 2.0.4+
  gql_websocket_link:
    git:
      url: https://github.com/agent3bood/gql.git
      path: links/gql_websocket_link
      ref: issue/294

dev_dependencies:
  artemis: ^6.18.4
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
```
