### ISSUE TITLE
Using same fragment for multiple schemas generates multiple identical classes

### ISSUE THREAD

**Issue by RobertBrunhage** [comigor/artemis#409]
## Bug description
Not sure if this is a bug or intended. But if you have two schemas and try to use a fragment between both schemas it will generate a identical class for both of the outputs.

Example: We have the same type of error between all mutations and schemas and want to have a single fragment for them. This is fine but it generates multiple identical Dart classes.

`SomeErrorMixin` // for schema 1
`SomeErrorMixin` // for schema 2

Is it possible to have a shared class that is used by both of the outputs with the generated code?

## Specs
Artemis version: 7.12.0-beta.1
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - data/**
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - output: "lib/src/api_one.graphql.dart"
              schema: "data/api_one/schema.graphql"
              queries_glob: "data/api_one/mutations_and_queries/**/*.graphql"
              fragments_glob: "data/common_fragments/*.graphql"
              naming_scheme: pathedWithFields
              type_name_field: __typename
              append_type_name: true

            - output: "lib/src/api_two.graphql.dart"
              schema: "data/api_two/schema.graphql"
              queries_glob: "data/api_two/mutations_and_queries/*.graphql"
              fragments_glob: "data/common_fragments/*.graphql"
              naming_scheme: pathedWithFields
              type_name_field: __typename
              append_type_name: true

```
</details>
