### ISSUE TITLE
Using third party types on custom scalars

### ISSUE THREAD

**Issue by miorimmax** [comigor/artemis#5]
Hey there! I'm exploring this library a bit, working good so far, but I got a custom scalar for `BigDecimal` that uses [decimal](https://pub.dev/packages/decimal) on the dart side, as you can see in my custom parser:

```dart
import 'package:decimal/decimal.dart';

Decimal fromGraphQLBigDecimalToDartDecimal(String value) => Decimal.parse(value);

String fromDartDecimalToGraphQLBigDecimal(Decimal value) => value.toString();
```

But the generated code does not build because it is missing a import for `package:decimal/decimal.dart`, so the compiler cannot figure out where `Decimal` is defined.

I'm editing the generated file and adding the import manually in order to be able to run my app.

Maybe we should have a `imports` array in the ScalarMap and inject the imports from there in the resulting file?

The build config would look like this:

```yaml
scalar_mapping:
  - graphql_type: BigDecimal
    dart_type: Decimal
    use_custom_parser: true
    imports: ['package:decimal/decimal.dart']
```

Another alternative I can think of is using a map, but that could make the logic a bit more complicated (to handle string or map):

```yaml
scalar_mapping:
  - graphql_type: BigDecimal
    dart_type:
      name: Decimal
      import: 'package:decimal/decimal.dart'
    use_custom_parser: true
```

WDYT? I can work on a PR to implement this on my spare time.
