### ISSUE TITLE
Error: Input types generated twice?

### ISSUE THREAD

**Issue by danielmahon** [comigor/artemis#93]
I get the following Exception when trying to use an `input type` from my downloaded schema... what am I missing? Thanks!

```
Exception: Two classes were generated with the same name `Tools$ToolOrderByInput$OrderByArg`!
You may want to:
- Make queries_glob stricter, to gather less .graphql files on a single output
- Use alias on one of the places a field of type `Tools$ToolOrderByInput$OrderByArg` is requested
- File a bug on artemis (https://is.gd/YLSfC2)
```

lib/graphql/queries.graphql
```gql
# Add [__typename] and [id] to every model you want cached

query tools($orderBy: ToolOrderByInput) {
  tools(orderBy: $orderBy) {
    __typename
    id
    name
    state
    updatedAt
  }
}
```

lib/graphql/schema.g.graphql (partial):
```gql
type Query {
  me: User!
  tool(where: ToolWhereUniqueInput!): Tool
  tools(orderBy: ToolOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Tool!]!
}

type Tool {
  id: String!
  name: String!
  isConnected: Boolean!
  state: String
  telemetryUpdatedAt: DateTime!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input ToolOrderByInput {
  id: OrderByArg
  createdAt: OrderByArg
  updatedAt: OrderByArg
  name: OrderByArg
  isConnected: OrderByArg
  state: OrderByArg
  telemetryUpdatedAt: OrderByArg
}

enum OrderByArg {
  asc
  desc
}
```

build.yaml
```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/schema.g.graphql
              queries_glob: lib/graphql/**[^.g].graphql
              output: lib/graphql/graphql.g.dart
              # resolve_type_field: __typename
```
